language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: raviten/special-barnacle
  bucket: bt-code-bucket
  region: ap-southeast-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: bt-code-bucket
  key: frontend-latest.zip
  bundle_type: zip
  application: britecore-frontend
  deployment_group: britecore
  region: ap-southeast-1
  on: *2

script:
  - zip -r frontend-latest *
  - mkdir -p dpl_cd_upload
  - mv frontend-latest.zip dpl_cd_upload/frontend-latest.zip